#!/bin/bash -xe

exec 2>&1

export JAVA_HOME=$(hab pkg path core/jre8)
export JENKINS_CONFIG={{pkg.svc_config_path}}
export JENKINS_HOME={{pkg.svc_config_path}}

exec java -jar {{pkg.path}}/jenkins.war
